server:
  port: 8083

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: productModule
          uri: lb://PRODUCT
          predicates:
            - Path=/api/v1/product/**
        - id: orderModule
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/order/**